# Generated by Django 4.1.4 on 2023-01-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_user_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, max_length=150)),
                ('state', models.TextField(blank=True, max_length=150)),
                ('district', models.TextField(blank=True, max_length=150)),
                ('town', models.TextField(blank=True, max_length=150)),
                ('H_No', models.TextField(blank=True, max_length=150)),
                ('pincode', models.IntegerField(blank=True)),
                ('payment_method', models.CharField(blank=True, choices=[('COD', 'Cash On Delivery')], max_length=150)),
            ],
        ),
    ]
